kind = "web"
previewPath = "/"
title = "Caixa 99 - Uber & 99"
version = "1.0.0"
id = "artifacts/caixa99"
router = "path"

[[services]]
name = "web"
paths = [ "/", "/moob-api" ]
localPort = 19730

[services.development]
run = "pnpm --filter @workspace/caixa99 run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/caixa99", "run", "build" ]
serve = "static"
publicDir = "artifacts/caixa99/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19730"
BASE_PATH = "/"
